n1 = input("첫 번째 숫자를 입력해주세요 > ")
print(int(n1))
n2 = input("두 번째 숫자를 입력해주세요 > ")
print(int(n1)+int(n2))
n3 = input("세 번째 숫자를 입력해주세요 > ")
print(int(n1)+int(n2)+int(n3))
n4 = input("네 번째 숫자를 입력해주세요 > ")
print(int(n1)+int(n2)+int(n3)+int(n4))
n5 = input("다섯 번째 숫자를 입력해주세요 > ")
print(int(n1)+int(n2)+int(n3)+int(n4)+int(n5))
